{% set setup_data = load_setup_py_data() %}
package:
  name: vamtoolbox
  version: {{ setup_data['version'] }}

source:
  path: ..

build:
  script: {{ PYTHON }} setup.py install

requirements:
  build:
    - python=3.10
    - setuptools
  run:
    - astra-toolbox=2.2.0
    - python=3.10
    - dill=0.3.8
    - opencv=4.10.0
    - pillow=10.4.0
    - matplotlib=3.9.2
    - pytorch::pytorch=2.4.0
    - pytorch::pytorch-cuda=12.4
    - pytorch::torchaudio=2.4.0
    - pytorch::torchvision=0.19.0
    - conda-forge::pyvista=0.44.1
    - pyglet=1.5.16
    - trimesh=4.4.7
    - tqdm=4.66.4
    - pyopengl=3.1.1a1
    - vedo=2024.5.1
    - scikit-image=0.23.2