{% set setup_data = load_setup_py_data() %}
package:
  name: vamtoolbox
  version: {{ setup_data['version'] }}

source:
  path: ..

build:
  script: {{ PYTHON }} setup.py install

requirements:
  build:
    - python=3.10
    - setuptools
  run:
    - astra-toolbox
    - python=3.10
    - dill
    - opencv
    - pillow
    - matplotlib
    - pytorch
    - pytorch-cuda=12.4
    - torchaudio
    - torchvision
    - conda-forge::pyvista
    - pyglet
    - trimesh
    - tqdm
    - pyopengl
    - vedo
    - scikit-image