{% set setup_data = load_setup_py_data() %}
package:
  name: vamtoolbox
  version: {{ setup_data['version'] }}

source:
  path: ..

build:
  script: {{ PYTHON }} setup.py install

requirements:
  build:
    - python=3.10
    - setuptools
  run:
  - astra-toolbox=2.1.0
  - asttokens=2.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blas=1.0
  - blosc=1.21.0
  - brotli=1.0.9
  - brotli-bin=1.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - certifi=2023.11.17
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - cloudpickle=2.0.0
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.1.0
  - cryptography=38.0.4
  - cuda-cccl=12.2.140
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.2.140
  - cuda-runtime=11.8.0
  - cudatoolkit=11.3.1
  - curl=7.55.1
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2.16.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - deprecated=1.2.14
  - dill=0.3.7
  - docutils=0.18.1
  - double-conversion=3.2.0
  - eigen=3.4.0
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - expat=2.5.0
  - ffmpeg=4.3.1
  - ffmpeg-python=0.2.0
  - filelock=3.9.0
  - fonttools=4.42.1
  - freeglut=3.2.2
  - freetype=2.12.1
  - future=0.18.3
  - giflib=5.2.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - hdf4=4.2.13
  - hdf5=1.12.1
  - icc_rt=2022.1.0
  - icu=68.2
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.31.1
  - intel-openmp=2023.1.0
  - ipykernel=6.19.2
  - ipython=8.15.0
  - jasper=2.0.33
  - jbig=2.1
  - jedi=0.19.0
  - jinja2=3.1.2
  - jpeg=9e
  - jsoncpp=1.9.5
  - jupyter_client=7.4.8
  - jupyter_core=5.1.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libastra=2.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.3.141
  - libcurand-dev=10.3.3.141
  - libcurl=7.88.1
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.8
  - libexpat=2.5.0
  - libffi=3.4.4
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnetcdf=4.8.1
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libogg=1.3.4
  - libopencv=4.5.5
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtheora=1.1.1
  - libtiff=4.4.0
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.4
  - libzip=1.5.1
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvmlite=0.41.0rc1
  - loguru=0.7.1
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.1
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nest-asyncio=1.5.6
  - networkx=3.1
  - numba=0.58.0rc1
  - numpy=1.25.2
  - numpy-base=1.25.2
  - opencv=4.5.5
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - packaging=23.1
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - platformdirs=2.5.2
  - pooch=1.7.0
  - proj=9.0.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.0
  - pugixml=1.11.4
  - pure_eval=0.2.2
  - py-opencv=4.5.5
  - pycparser=2.21
  - pyglet=1.5.27
  - pygments=2.16.1
  - pyopengl=3.1.6
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyvista=0.42.1
  - pywavelets=1.4.1
  - pywin32=305
  - pyzmq=23.2.0
  - qt=5.12.9
  - requests=2.31.0
  - scikit-image=0.19.3
  - scipy=1.11.1
  - scooby=0.7.2
  - setuptools=68.0.0
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.41.2
  - stack_data=0.6.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - tbb-devel=2021.8.0
  - tifffile=2021.7.2
  - tk=8.6.12
  - toolz=0.12.0
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.9.0
  - trimesh=4.0.4
  - typing_extensions=4.7.1
  - tzdata=2023c
  - ucrt=10.0.22621.0
  - unicodedata2=15.0.0
  - urllib3=1.26.16
  - utfcpp=3.2.4
  - vc=14.2
  - vc14_runtime=14.36.32532
  - vedo=2023.4.6
  - vs2015_runtime=14.36.32532
  - vtk=9.1.0
  - wcwidth=0.2.6
  - wheel=0.38.4
  - win32_setctime=1.1.0
  - win_inet_pton=1.1.0
  - wrapt=1.15.0
  - xz=5.4.2
  - zeromq=4.3.4
  - zfp=0.5.5
  - zlib=1.2.13
  - zstd=1.4.9
  - torchaudio=2.0.2
  - torchvision=0.15.2

  test:
    imports:
      - {{ setup_data['name'] }}
     
  about:
    home: "https://github.com/computed-axial-lithography/VAMToolbox"
    doc_url: "https://vamtoolbox.readthedocs.io/"
    dev_url: "https://github.com/computed-axial-lithography/VAMToolbox"
    license: "GNU GPLv3"
    license_family: "GNU GPL"
    summary: "Python library to support the generation of the light projections and the control of a DLP projector for tomographic volumetric additive manufacturing."