{% set setup_data = load_setup_py_data() %}
package:
  name: vamtoolbox
  version: {{ setup_data['version'] }}

source:
  path: ..

build:
  script: {{ PYTHON }} setup.py install

requirements:
  build:
    - python=3.10
    - setuptools
  run:
    - astra-toolbox
    - python=3.10
    - dill
    - opencv
    - pillow
    - matplotlib=3.6.3
    - pytorch::pytorch
    - pytorch::pytorch-cuda
    - pytorch::torchaudio
    - pytorch::torchvision
    - conda-forge::pyvista
    - pyglet=1.5.27
    - trimesh
    - tqdm
    - pyopengl
    - vedo=2023.4.6
    - scikit-image